version: '3'
services:
  web:
    build: .
    command: python3 ./practicaCursoDocker/djangoAppDocker/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/django-app
    ports:
      - "8000:8000"